---
:api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
:password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
:store: store.myshopify.com
:theme_id: 
:ignore_files:
- .sass-cache/*
- sass/*
- .gitignore
- .ruby-version
- config.rb
- Gemfile
- Rakefile
- README